// apps/frontend/src/pages/EvalSetsPage.vue
<script setup lang="ts">
import clsx from "clsx";
import { ArrowDown, ArrowUp, Copy, Download, Link2, Plus, Search, Trash2 } from "lucide-vue-next";
import { computed, ref, watch } from "vue";
import DropdownSelect from "../components/DropdownSelect.vue";
import type { DropdownSelectOption } from "../components/dropdown";
import CaseStepTimeline from "../features/evaluation/components/CaseStepTimeline.vue";
import EvalCaseEditor from "../features/evaluation/components/EvalCaseEditor.vue";
import EvalCaseLibraryPanel from "../features/evaluation/components/EvalCaseLibraryPanel.vue";
import EvalSetSwitcher from "../features/evaluation/components/EvalSetSwitcher.vue";
import { useEvalSetManagement } from "../features/evaluation/composables/useEvalSetManagement";
import { workspaceFileName } from "../features/evaluation/lib/evalCaseManagement";
import { api, ApiError } from "../lib/api";
import { compactText, humanDate } from "../lib/format";
import type { RouteState } from "../lib/navigation";
import type { SkillDetail, ToastState } from "../types";

const props = defineProps<{ skill: SkillDetail; selectedCaseId: string | null; selectedEvalSetId: string | null }>();
const emit = defineEmits<{ navigate: [next: Partial<RouteState>]; refresh: []; toast: [toast: ToastState] }>();

const skillRef = computed(() => props.skill);
const selectedCaseIdRef = computed(() => props.selectedCaseId);
const selectedEvalSetIdRef = computed(() => props.selectedEvalSetId);

const manager = useEvalSetManagement({
  skill: skillRef,
  selectedCaseId: selectedCaseIdRef,
  selectedEvalSetId: selectedEvalSetIdRef,
  navigate: (next) => emit("navigate", next),
  refresh: () => emit("refresh"),
  toast: (toast) => emit("toast", toast),
});
const sharedEvalSetNames = ref<string[]>([]);
const canManageEval = computed(() => Boolean(props.skill.capabilities?.permissions["eval.manage"]));

const caseSortOptions: DropdownSelectOption[] = [
  { value: "position", label: "按列表顺序" },
  { value: "title", label: "按标题排序" },
  { value: "version", label: "按版本排序" },
];

watch(() => manager.selected.value?.case.id, async (caseId) => {
  if (!caseId) {
    sharedEvalSetNames.value = [];
    return;
  }
  try {
    const history = await api.getEvalCaseHistory(caseId);
    const currentEvalSetId = manager.selectedEvalSetId.value;
    const memberships = history.versions[0]?.included_in_eval_sets ?? [];
    sharedEvalSetNames.value = memberships
      .filter((membership) => membership.eval_set_id !== currentEvalSetId)
      .map((membership) => membership.name);
  } catch {
    sharedEvalSetNames.value = [];
  }
}, { immediate: true });

/** 复制详情中的步骤、备注等文本内容。 */
async function copyText(value?: string | null): Promise<void> {
  const text = compactText(value, "无内容");
  try {
    await navigator.clipboard.writeText(text);
  } catch (caught) {
    emit("toast", { tone: "danger", message: errorMessage(caught) });
  }
}

function errorMessage(caught: unknown): string {
  if (caught instanceof ApiError || caught instanceof Error) return caught.message;
  return "操作失败。";
}
</script>

<template>
  <div class="evalset-layout">
    <aside class="case-sidebar">
      <label class="search-field compact">
        <Search :size="18" />
        <input v-model="manager.query.value" placeholder="搜索测试例">
      </label>
      <div class="case-toolbar">
        <label class="case-sort-control">
          <DropdownSelect v-model="manager.caseSort.value" :options="caseSortOptions" aria-label="测试例排序" compact />
        </label>
        <div class="case-toolbar-actions">
          <button class="primary-button" type="button" :disabled="!canManageEval" @click="manager.startCreate"><Plus :size="17" />新建测试例</button>
          <button class="secondary-button" type="button" :disabled="!canManageEval" @click="manager.openLibrary"><Link2 :size="17" />添加已有</button>
        </div>
      </div>
      <p v-if="!canManageEval" class="field-help permission-hint">当前身份没有管理测评集和测试例的权限。</p>
      <EvalCaseLibraryPanel
        v-if="manager.libraryOpen.value"
        :busy="manager.busy.value"
        :items="manager.libraryItems.value"
        @add="manager.addExistingCase"
        @close="manager.libraryOpen.value = false"
      />
      <div class="case-list">
        <button
          v-if="manager.editingMode.value === 'create'"
          type="button"
          :class="clsx('case-row', 'draft', manager.draftSelected.value && 'active')"
          @click="manager.draftSelected.value = true"
        >
          <span class="case-position-mark">新</span>
          <span class="case-row-copy">
            <span class="case-row-topline"><strong class="case-row-title">新测试例（未保存）</strong></span>
            <span class="case-row-metadata">
              <span class="case-current-chip">填写后保存到当前测评集</span>
              <span class="case-draft-chip"><span class="case-draft-dot" />草稿</span>
            </span>
          </span>
        </button>
        <button
          v-for="item in manager.cases.value"
          :key="item.case.id"
          :class="clsx('case-row', manager.activeCaseRowId.value === item.case.id && 'active')"
          type="button"
          @click="manager.selectCase(item)"
        >
          <span class="case-position-mark">#{{ item.position + 1 }}</span>
          <span class="case-row-copy">
            <span class="case-row-topline"><strong class="case-row-title">{{ item.case.title }}</strong></span>
            <span class="case-row-metadata">
              <span class="case-version-pill">测试例 v{{ item.case_version.version_number }}</span>
              <span class="case-time-chip">创建 {{ humanDate(item.case.created_at) }}</span>
              <span class="case-time-chip">更新 {{ humanDate(item.case.updated_at) }}</span>
            </span>
          </span>
        </button>
      </div>
      <p class="case-count">共 {{ manager.detail.value?.cases.length ?? 0 }} 个测试例</p>
    </aside>

    <section class="evalset-main">
      <EvalSetSwitcher
        :active="manager.evalSet.value"
        :busy="manager.busy.value"
        :case-count="manager.detail.value?.cases.length ?? 0"
        :disabled="!canManageEval"
        :eval-sets="manager.evalSets.value"
        :selected-id="manager.selectedEvalSetId.value"
        @create="manager.createEvalSet"
        @select="manager.selectEvalSet"
        @update="manager.updateEvalSet"
      />
      <section class="case-detail">
        <EvalCaseEditor
          v-if="manager.editingMode.value"
          :key="manager.editingMode.value === 'create' ? 'new' : manager.editingCase.value?.case.id"
          :case-item="manager.editingMode.value === 'edit' ? manager.editingCase.value : null"
          :busy="manager.busy.value"
          :title="manager.editorTitle.value"
          :status-label="manager.editorStatus.value"
          @cancel="manager.cancelEditor"
          @submit="manager.saveCase"
        />
        <template v-else-if="manager.selected.value">
          <header class="case-detail-head">
            <div>
              <h1>{{ manager.selected.value.case.title }}</h1>
              <div class="tag-row">
                <span class="tag-chip">测试例 v{{ manager.selected.value.case_version.version_number }}</span>
                <span class="tag-chip">位置 {{ manager.selected.value.position + 1 }}</span>
                <span class="tag-chip">创建 {{ humanDate(manager.selected.value.case.created_at) }}</span>
                <span class="tag-chip">更新 {{ humanDate(manager.selected.value.case.updated_at) }}</span>
                <a
                  v-if="manager.selected.value.case_version.workspace_artifact"
                  class="tag-chip"
                  :href="api.artifactDownloadUrl(manager.selected.value.case_version.workspace_artifact.id)"
                  :download="workspaceFileName(manager.selected.value.case_version.workspace_artifact.locator)"
                >
                  <Download :size="14" />
                  {{ workspaceFileName(manager.selected.value.case_version.workspace_artifact.locator) }}
                </a>
              </div>
              <p v-if="sharedEvalSetNames.length" class="case-shared-hint">
                这个测试例还被 {{ sharedEvalSetNames.join("、") }} 引用；编辑后会同步影响所有引用它的测评集。
              </p>
            </div>
            <div class="button-row">
              <button
                class="secondary-button"
                type="button"
                :disabled="!canManageEval || manager.caseSort.value !== 'position' || manager.selected.value.position === 0"
                @click="manager.moveCase(manager.selected.value, -1)"
              >
                <ArrowUp :size="16" />
                上移
              </button>
              <button
                class="secondary-button"
                type="button"
                :disabled="!canManageEval || manager.caseSort.value !== 'position' || manager.selected.value.position >= (manager.detail.value?.cases.length ?? 1) - 1"
                @click="manager.moveCase(manager.selected.value, 1)"
              >
                <ArrowDown :size="16" />
                下移
              </button>
              <button class="secondary-button" type="button" :disabled="!canManageEval" @click="manager.removeCase(manager.selected.value)">
                <Trash2 :size="16" />
                移除引用
              </button>
              <button class="secondary-button" type="button" :disabled="!canManageEval || manager.busy.value" @click="manager.copyCase(manager.selected.value)">
                <Copy :size="16" />
                复制测试例
              </button>
              <button class="primary-button" type="button" :disabled="!canManageEval" @click="manager.startEdit(manager.selected.value)">编辑测试例</button>
            </div>
          </header>
          <CaseStepTimeline :steps="manager.selected.value.case_version.steps" @copy="copyText" />
          <section class="case-block">
            <header>
              <h2>备注</h2>
              <button class="icon-button mini" type="button" aria-label="复制备注" @click="copyText(manager.selected.value.case_version.notes)"><Copy :size="16" /></button>
            </header>
            <pre>{{ compactText(manager.selected.value.case_version.notes, "无内容") }}</pre>
          </section>
        </template>
        <div v-else class="quiet-panel">
          <strong>选择一个测试例查看详情</strong>
          <p>也可以在左侧新建测试例，或把 Skill 中已有的测试例加入当前测评集。</p>
        </div>
      </section>
    </section>
  </div>
</template>

// apps/web-v4/src/pages/EvalSetsPage.tsx
import clsx from "clsx";
import { Copy, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { CaseVersionRoadmap } from "../components/CaseVersionRoadmap";
import { EvalCaseModal, type EvalCaseFormData } from "../components/EvalCaseModal";
import { api, ApiError } from "../lib/api";
import { compactText, humanDate } from "../lib/format";
import type { RouteState } from "../lib/navigation";
import type { EvalCaseHistory, EvalSetCase, EvalSetVersionDetail, SkillDetail, ToastState } from "../types";

type EvalSetsPageProps = {
  skill: SkillDetail;
  selectedCaseId: string | null;
  onNavigate: (next: Partial<RouteState>) => void;
  onRefresh: () => Promise<void>;
  onToast: (toast: ToastState) => void;
};

type CaseSortKey = "position" | "title" | "version";

export function EvalSetsPage({ skill, selectedCaseId, onNavigate, onRefresh, onToast }: EvalSetsPageProps) {
  const evalSet = skill.summary.primary_eval_set;
  const versionId = evalSet?.current_version_id;
  const [detail, setDetail] = useState<EvalSetVersionDetail | null>(null);
  const [query, setQuery] = useState("");
  const [caseFilter, setCaseFilter] = useState<"all" | "active">("all");
  const [caseSort, setCaseSort] = useState<CaseSortKey>("position");
  const [editor, setEditor] = useState<EvalSetCase | "new" | null>(null);
  const [history, setHistory] = useState<EvalCaseHistory | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!versionId) return;
    api.getEvalSetVersion(versionId).then(setDetail).catch((error) => onToast({ tone: "danger", message: errorMessage(error) }));
  }, [onToast, versionId]);

  const cases = useMemo(() => sortCases(filterCases(detail?.cases ?? [], query, caseFilter), caseSort), [caseFilter, caseSort, detail, query]);
  const selected = cases.find((item) => item.case.id === selectedCaseId) ?? cases[0] ?? null;

  useEffect(() => {
    if (!selected || selected.case.id === selectedCaseId) return;
    onNavigate({ selectedCaseId: selected.case.id });
  }, [onNavigate, selected, selectedCaseId]);

  useEffect(() => {
    if (!selected) {
      setHistory(null);
      return;
    }
    api.getEvalCaseHistory(selected.case.id).then(setHistory).catch(() => setHistory(null));
  }, [selected]);

  async function saveCase(form: EvalCaseFormData) {
    setBusy(true);
    try {
      if (editor === "new") await api.createEvalCase({ skill_id: skill.skill.id, ...form });
      else if (editor) await api.updateEvalCase(editor.case.id, { ...form, make_current: true });
      setEditor(null);
      onToast({ tone: "success", message: "测评集已更新为新版本。" });
      await onRefresh();
    } catch (caught) {
      onToast({ tone: "danger", message: errorMessage(caught) });
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="evalset-layout">
      <aside className="case-sidebar">
        <span className="back-link">当前测评集</span>
        <div className="evalset-card">
          <div className="evalset-title-row">
            <span className="green-dot" />
            <span>当前 EvalSetVersion</span>
          </div>
          <h1>{evalSet?.name ?? "Regression Set"} v{evalSet?.current_version?.version_number ?? "-"}</h1>
          <div className="mini-grid">
            <span>Cases<b>{detail?.cases.length ?? 0}</b></span>
            <span>版本<b>v{evalSet?.current_version?.version_number ?? "-"}</b></span>
            <span>更新时间<b>{humanDate(evalSet?.current_version?.created_at)}</b></span>
          </div>
        </div>
        <label className="search-field compact">
          <Search size={18} />
          <input value={query} placeholder="搜索 case" onChange={(event) => setQuery(event.target.value)} />
        </label>
        <div className="case-toolbar">
          <button className={clsx("select-button", caseFilter === "all" && "active")} type="button" onClick={() => setCaseFilter("all")}>
            全部
          </button>
          <button className={clsx("select-button", caseFilter === "active" && "active")} type="button" onClick={() => setCaseFilter("active")}>
            仅活跃
          </button>
          <label className="case-sort-control">
            <select aria-label="Case 排序" value={caseSort} onChange={(event) => setCaseSort(event.target.value as CaseSortKey)}>
              <option value="position">按列表顺序</option>
              <option value="title">按标题排序</option>
              <option value="version">按版本排序</option>
            </select>
          </label>
          <button className="primary-button" type="button" onClick={() => setEditor("new")}>
            <Plus size={17} />
            添加
          </button>
        </div>
        <div className="case-list">
          {cases.map((item) => {
            const isCurrentCaseVersion = item.case.current_version_id === item.case_version.id;
            const lifecycleLabel = caseLifecycleLabel(item.case.lifecycle_status);
            return (
              <button
                aria-label={`${item.case.title}，#${item.position + 1}，case v${item.case_version.version_number}，${isCurrentCaseVersion ? "当前版本" : "历史版本"}，${lifecycleLabel}`}
                className={clsx("case-row", selected?.case.id === item.case.id && "active")}
                type="button"
                key={item.case.id}
                onClick={() => onNavigate({ selectedCaseId: item.case.id })}
              >
                <span className="case-position-mark">#{item.position + 1}</span>
                <span className="case-row-copy">
                  <span className="case-row-topline">
                    <strong className="case-row-title">{item.case.title}</strong>
                  </span>
                  <span className="case-row-metadata">
                    <span className="case-version-pill">case v{item.case_version.version_number}</span>
                    <span className={clsx("case-current-chip", !isCurrentCaseVersion && "muted")}>
                      {isCurrentCaseVersion ? "当前" : "历史"}
                    </span>
                    <span className={clsx("case-status-chip", item.case.lifecycle_status !== "active" && "muted")}>
                      <span className="case-status-dot" />
                      {lifecycleLabel}
                    </span>
                  </span>
                </span>
              </button>
            );
          })}
        </div>
        <p className="case-count">共 {detail?.cases.length ?? 0} 个 case</p>
      </aside>

      <section className="case-detail">
        {selected ? (
          <>
            <header className="case-detail-head">
              <div>
                <h1>{selected.case.title}</h1>
                <div className="tag-row">
                  <span className="tag-chip">case v{selected.case_version.version_number}</span>
                  <span className="tag-chip">position {selected.position + 1}</span>
                </div>
              </div>
              <div className="button-row">
                <button className="primary-button" type="button" onClick={() => setEditor(selected)}>
                  编辑为新版本
                </button>
              </div>
            </header>
            <CaseBlock title="Input" text={selected.case_version.input_artifact.content_text} />
            <CaseBlock title="Expected output" text={selected.case_version.expected_output_artifact.content_text} />
            <CaseBlock title="Notes" text={selected.case_version.notes} />
            <CaseVersionRoadmap history={history} currentVersionId={selected.case_version.id} />
          </>
        ) : (
          <div className="quiet-panel">还没有测试用例。</div>
        )}
      </section>

      {editor ? <EvalCaseModal caseItem={editor === "new" ? null : editor} busy={busy} onClose={() => setEditor(null)} onSubmit={saveCase} /> : null}
    </div>
  );
}

function CaseBlock({ title, text }: { title: string; text?: string | null }) {
  const value = compactText(text, "无内容");
  return (
    <section className="case-block">
      <header>
        <h2>{title}</h2>
        <button className="icon-button mini" type="button" aria-label={`复制 ${title}`} onClick={() => navigator.clipboard.writeText(value)}>
          <Copy size={16} />
        </button>
      </header>
      <pre>{value}</pre>
    </section>
  );
}

function filterCases(cases: EvalSetCase[], query: string, filter: "all" | "active"): EvalSetCase[] {
  const normalized = query.trim().toLowerCase();
  return cases.filter((item) => {
    if (filter === "active" && item.case.lifecycle_status !== "active") return false;
    if (!normalized) return true;
    return [item.case.title, item.case_version.input_artifact.content_text, item.case_version.expected_output_artifact.content_text].join(" ").toLowerCase().includes(normalized);
  });
}

function sortCases(cases: EvalSetCase[], sortKey: CaseSortKey): EvalSetCase[] {
  const copy = [...cases];
  if (sortKey === "title") return copy.sort((left, right) => left.case.title.localeCompare(right.case.title) || left.position - right.position);
  if (sortKey === "version") {
    return copy.sort((left, right) => right.case_version.version_number - left.case_version.version_number || left.position - right.position);
  }
  return copy.sort((left, right) => left.position - right.position);
}

function caseLifecycleLabel(status: string): string {
  if (status === "active") return "活跃";
  if (status === "archived") return "归档";
  return status || "未知";
}

function errorMessage(error: unknown): string {
  if (error instanceof ApiError || error instanceof Error) return error.message;
  return "操作失败。";
}
