// apps/web/src/pages/SkillPage.vue
<script setup lang="ts">
import { Upload } from "lucide-vue-next";
import { computed, ref, watch } from "vue";
import SkillTabs from "../components/Tabs.vue";
import type { RouteState, SkillTab } from "../lib/navigation";
import type { SkillDetail, ToastState } from "../types";
import EvalSetsPage from "./EvalSetsPage.vue";
import EvaluatePage from "./EvaluatePage.vue";
import HistoryPage from "./HistoryPage.vue";
import OverviewPage from "./OverviewPage.vue";
import UploadVersionModal from "./UploadVersionModal.vue";
import VersionsPage from "./VersionsPage.vue";

const props = defineProps<{ skill: SkillDetail; tab: SkillTab; route: RouteState }>();
const emit = defineEmits<{
  tab: [tab: SkillTab];
  refresh: [];
  navigate: [next: Partial<RouteState>];
  toast: [toast: ToastState];
}>();

const uploadOpen = ref(false);
const canUploadVersion = computed(() => props.tab === "overview" || props.tab === "versions");

watch(() => [props.skill.skill.id, props.tab] as const, () => {
  uploadOpen.value = false;
});

function finishUpload(): void {
  uploadOpen.value = false;
  emit("toast", { tone: "success", message: "版本已上传。" });
  emit("refresh");
}
</script>

<template>
  <div class="skill-page">
    <div class="skill-nav-row">
      <SkillTabs :active="tab" @change="emit('tab', $event)" />
      <button v-if="canUploadVersion" class="primary-button" type="button" @click="uploadOpen = true">
        <Upload :size="17" />
        上传版本
      </button>
    </div>

    <OverviewPage v-if="tab === 'overview'" :skill="skill" @navigate="emit('navigate', $event)" />
    <VersionsPage
      v-else-if="tab === 'versions'"
      :skill="skill"
      :selected-version-id="route.selectedVersionId"
      :upload-open="uploadOpen"
      @navigate="emit('navigate', $event)"
      @upload-close="uploadOpen = false"
      @uploaded="finishUpload"
      @refresh="emit('refresh')"
      @toast="emit('toast', $event)"
    />
    <EvalSetsPage
      v-else-if="tab === 'evalsets'"
      :skill="skill"
      :selected-case-id="route.selectedCaseId"
      @navigate="emit('navigate', $event)"
      @refresh="emit('refresh')"
      @toast="emit('toast', $event)"
    />
    <EvaluatePage
      v-else-if="tab === 'evaluate'"
      :skill="skill"
      @refresh="emit('refresh')"
      @navigate="emit('navigate', $event)"
      @toast="emit('toast', $event)"
    />
    <HistoryPage
      v-else-if="tab === 'history'"
      :skill="skill"
      :selected-run-id="route.selectedRunId"
      @navigate="emit('navigate', $event)"
      @toast="emit('toast', $event)"
    />

    <UploadVersionModal v-if="uploadOpen && tab === 'overview'" :skill="skill" @close="uploadOpen = false" @uploaded="finishUpload" />
  </div>
</template>

// apps/web-v4/src/pages/SkillPage.tsx
import { Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { SkillTabs } from "../components/Tabs";
import type { RouteState, SkillTab } from "../lib/navigation";
import { EvalSetsPage } from "./EvalSetsPage";
import { EvaluatePage } from "./EvaluatePage";
import { HistoryPage } from "./HistoryPage";
import { OverviewPage } from "./OverviewPage";
import { UploadVersionModal } from "./UploadVersionModal";
import { VersionsPage } from "./VersionsPage";
import type { SkillDetail, ToastState } from "../types";

type SkillPageProps = {
  skill: SkillDetail;
  tab: SkillTab;
  route: RouteState;
  onTab: (tab: SkillTab) => void;
  onRefresh: () => Promise<void>;
  onNavigate: (next: Partial<RouteState>) => void;
  onToast: (toast: ToastState) => void;
};

export function SkillPage({ skill, tab, route, onTab, onRefresh, onNavigate, onToast }: SkillPageProps) {
  const [uploadOpen, setUploadOpen] = useState(false);
  const canUploadVersion = tab === "overview" || tab === "versions";
  const closeUpload = () => setUploadOpen(false);

  useEffect(() => {
    setUploadOpen(false);
  }, [skill.skill.id, tab]);

  async function finishUpload() {
    closeUpload();
    onToast({ tone: "success", message: "版本已上传。" });
    await onRefresh();
  }

  return (
    <div className="skill-page">
      <div className="skill-nav-row">
        <SkillTabs active={tab} onChange={onTab} />
        {canUploadVersion ? (
          <button className="primary-button" type="button" onClick={() => setUploadOpen(true)}>
            <Upload size={17} />
            上传版本
          </button>
        ) : null}
      </div>

      {tab === "overview" ? <OverviewPage skill={skill} onNavigate={onNavigate} /> : null}
      {tab === "versions" ? (
        <VersionsPage
          skill={skill}
          selectedVersionId={route.selectedVersionId}
          uploadOpen={uploadOpen}
          onNavigate={onNavigate}
          onUploadClose={closeUpload}
          onUploaded={finishUpload}
        />
      ) : null}
      {tab === "evalsets" ? <EvalSetsPage skill={skill} selectedCaseId={route.selectedCaseId} onNavigate={onNavigate} onRefresh={onRefresh} onToast={onToast} /> : null}
      {tab === "evaluate" ? <EvaluatePage skill={skill} onRefresh={onRefresh} onNavigate={onNavigate} onToast={onToast} /> : null}
      {tab === "history" ? <HistoryPage skill={skill} selectedRunId={route.selectedRunId} onNavigate={onNavigate} onToast={onToast} /> : null}

      {uploadOpen && tab === "overview" ? (
        <UploadVersionModal
          skill={skill}
          onClose={closeUpload}
          onUploaded={finishUpload}
        />
      ) : null}
    </div>
  );
}
