// apps/web/src/pages/VersionsPage.vue
<script setup lang="ts">
import clsx from "clsx";
import { FileText, Pencil, Save, SquarePen, X } from "lucide-vue-next";
import { computed, ref, watch } from "vue";
import BundleBrowser from "../components/BundleBrowser.vue";
import BundleDiffPanel from "../components/BundleDiffPanel.vue";
import { api, ApiError } from "../lib/api";
import { compactText, humanDate, scoreKind, scoreLabel, versionName } from "../lib/format";
import { compactDigest } from "../lib/history";
import type { RouteState } from "../lib/navigation";
import type { EvalRunRecord, SkillDetail, SkillVersion, ToastState } from "../types";
import SkillEditForm from "./SkillEditForm.vue";
import VersionUploadForm from "./VersionUploadForm.vue";

const props = defineProps<{ skill: SkillDetail; selectedVersionId: string | null; uploadOpen: boolean }>();
const emit = defineEmits<{
  navigate: [next: Partial<RouteState>];
  "upload-close": [];
  uploaded: [];
  refresh: [];
  toast: [toast: ToastState];
}>();

const editOpen = ref(false);
const selected = computed(() => props.skill.versions.find((version) => version.id === props.selectedVersionId) ?? props.skill.summary.current_version ?? props.skill.versions[0] ?? null);
const previous = computed(() => (selected.value ? previousSkillVersion(props.skill.versions, selected.value) : null));
const evalSetName = computed(() => props.skill.summary.primary_eval_set?.name ?? "未绑定");
const latestRun = computed(() => (selected.value ? latestRunForVersion(selected.value, props.skill.latest_eval_runs) : null));
const files = computed(() => selected.value?.bundle_files ?? []);

watch(() => props.uploadOpen, (open) => {
  if (open) editOpen.value = false;
});

async function renameSelected(displayName: string | null): Promise<void> {
  if (!selected.value) return;
  try {
    await api.updateSkillVersionName(selected.value.id, displayName);
    emit("toast", { tone: "success", message: "Skill 版本名称已更新。" });
    emit("refresh");
  } catch (caught) {
    emit("toast", { tone: "danger", message: errorMessage(caught) });
  }
}

function finishEdit(): void {
  editOpen.value = false;
  emit("toast", { tone: "success", message: "Skill 已保存为新版本。" });
  emit("refresh");
}

function previousSkillVersion(versions: SkillVersion[], current: SkillVersion): SkillVersion | null {
  return [...versions]
    .filter((version) => version.version_number < current.version_number)
    .sort((left, right) => right.version_number - left.version_number)[0] ?? null;
}

function latestRunForVersion(version: SkillVersion, runs: EvalRunRecord[]): EvalRunRecord | null {
  return [...runs]
    .filter((run) => run.skill_version_id === version.id)
    .sort((left, right) => Date.parse(right.created_at ?? "") - Date.parse(left.created_at ?? ""))[0] ?? null;
}

function errorMessage(caught: unknown): string {
  if (caught instanceof ApiError || caught instanceof Error) return caught.message;
  return "操作失败。";
}
</script>

<template>
  <div v-if="!selected" class="quiet-panel">还没有版本。</div>
  <div v-else :class="clsx('versions-workspace', uploadOpen && 'with-upload-panel')">
    <section class="skill-summary-panel version-summary-panel">
      <div class="skill-title-block">
        <dl class="skill-identity-card" aria-label="版本身份信息">
          <div>
            <dt>Skill</dt>
            <dd>{{ skill.skill.slug }}/</dd>
          </div>
          <div>
            <dt>内容 digest</dt>
            <dd>{{ compactDigest(selected.content_digest) }}</dd>
          </div>
          <div>
            <dt>创建者</dt>
            <dd>{{ selected.created_by }}</dd>
          </div>
        </dl>
        <div class="skill-title-copy">
          <VersionNameEditor :version="selected" @save="renameSelected" />
          <p>{{ compactText(selected.change_summary, "这个版本还没有说明。") }}</p>
        </div>
      </div>
      <div class="summary-metric">
        <span>节点</span>
        <strong>{{ versionName(selected) }}</strong>
        <small>{{ selected.id === skill.skill.current_version_id ? "当前版本" : "历史版本" }}</small>
      </div>
      <div class="summary-metric">
        <span>最新得分</span>
        <strong :class="scoreKind(latestRun)">{{ scoreLabel(latestRun) }}</strong>
        <small>{{ latestRun?.summary?.total ? `${latestRun.summary.passed ?? 0}/${latestRun.summary.total} 通过` : "尚无测评" }}</small>
      </div>
      <div class="summary-metric">
        <span>测评集</span>
        <strong class="summary-value-chip">{{ evalSetName }}</strong>
        <small>运行环境保存在 EvalRun</small>
      </div>
    </section>

    <section class="version-node-strip" aria-label="Skill 版本节点">
      <button
        v-for="version in skill.versions"
        :key="version.id"
        :class="clsx('version-node', selected.id === version.id && 'active')"
        type="button"
        @click="emit('navigate', { selectedVersionId: version.id })"
      >
        <span>{{ versionName(version) }}</span>
        <small>{{ version.id === skill.skill.current_version_id ? "当前" : humanDate(version.created_at) }}</small>
      </button>
    </section>

    <section v-if="uploadOpen" class="version-upload-panel" aria-label="上传新版本">
      <div class="version-upload-head">
        <div>
          <h2>上传新版本</h2>
          <p>上传标准 Skill bundle 后会追加一个不可变 SkillVersion。</p>
        </div>
        <button class="icon-button" type="button" aria-label="关闭上传面板" @click="emit('upload-close')">
          <X :size="18" />
        </button>
      </div>
      <VersionUploadForm :skill="skill" actions-class-name="version-upload-actions" @cancel="emit('upload-close')" @uploaded="emit('uploaded')" />
    </section>

    <section v-if="editOpen" class="version-upload-panel" aria-label="编辑 Skill 内容">
      <div class="version-upload-head">
        <div>
          <h2>编辑 Skill</h2>
          <p>基于当前选中的不可变版本创建新 SkillVersion。</p>
        </div>
        <button class="icon-button" type="button" aria-label="关闭编辑面板" @click="editOpen = false">
          <X :size="18" />
        </button>
      </div>
      <SkillEditForm
        :key="selected.id"
        :skill="skill"
        :version="selected"
        actions-class-name="version-upload-actions"
        @cancel="editOpen = false"
        @saved="finishEdit"
      />
    </section>

    <section class="version-files-panel">
      <div class="panel-title-row">
        <h2>Bundle 内容</h2>
        <div class="button-row">
          <span class="version-meta-line">
            <FileText :size="16" />
            {{ files.length }} 个文件 · {{ humanDate(selected.created_at) }}
          </span>
          <button class="secondary-button" type="button" @click="() => { emit('upload-close'); editOpen = true; }">
            <SquarePen :size="16" />
            编辑 Skill
          </button>
        </div>
      </div>
      <BundleBrowser :files="files" :root-label="skill.skill.slug" />
    </section>

    <BundleDiffPanel :current="selected" :previous="previous" :versions="skill.versions" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

const VersionNameEditor = defineComponent({
  props: {
    version: { type: Object as () => SkillVersion, required: true },
  },
  emits: ["save"],
  setup(editorProps, { emit }) {
    const editing = ref(false);
    const draft = ref(editorProps.version.display_name ?? "");
    const busy = ref(false);

    async function save() {
      busy.value = true;
      try {
        await emit("save", cleanName(draft.value));
        editing.value = false;
      } finally {
        busy.value = false;
      }
    }

    return { editing, draft, busy, save, cleanName, versionName, Save, X, Pencil };
  },
  template: `
    <div v-if="editing" class="version-name-editor">
      <input v-model="draft" maxlength="80" :placeholder="\`v\${version.version_number}\`" />
      <button class="icon-button" type="button" aria-label="保存版本名称" :disabled="busy" @click="save">
        <Save :size="17" />
      </button>
      <button class="icon-button" type="button" aria-label="取消命名" @click="editing = false">
        <X :size="17" />
      </button>
    </div>
    <div v-else class="version-title-row">
      <h1>{{ versionName(version) }}</h1>
      <span v-if="version.display_name" class="version-number-badge">v{{ version.version_number }}</span>
      <button class="icon-button" type="button" aria-label="命名 Skill 版本" @click="editing = true">
        <Pencil :size="17" />
      </button>
    </div>
  `,
});

function cleanName(value: string): string | null {
  const clean = value.trim();
  return clean || null;
}
</script>

// apps/web-v4/src/pages/VersionsPage.tsx
import clsx from "clsx";
import { CheckCircle2, Grid2X2, List, X } from "lucide-react";
import { useState } from "react";
import { VersionInspector } from "../components/VersionInspector";
import { scoreKind, scoreLabel, versionName } from "../lib/format";
import type { RouteState } from "../lib/navigation";
import type { EvalRunRecord, SkillDetail, SkillVersion } from "../types";
import { VersionUploadForm } from "./VersionUploadForm";

type VersionsPageProps = {
  skill: SkillDetail;
  selectedVersionId: string | null;
  uploadOpen: boolean;
  onNavigate: (next: Partial<RouteState>) => void;
  onUploadClose: () => void;
  onUploaded: () => Promise<void>;
};

export function VersionsPage({ skill, selectedVersionId, uploadOpen, onNavigate, onUploadClose, onUploaded }: VersionsPageProps) {
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const selected = skill.versions.find((version) => version.id === selectedVersionId) ?? skill.summary.current_version ?? skill.versions[0] ?? null;
  const evalSetName = skill.summary.primary_eval_set?.name ?? "未绑定";

  return (
    <div className={clsx("versions-layout", uploadOpen && "with-upload-panel")}>
      <section className="version-board">
        <header className="section-heading">
          <div>
            <h1>版本</h1>
            <p>SkillVersion 是不可变内容快照；运行环境标签记录在每次 EvalRun 上。</p>
          </div>
        </header>
        <div className="version-toolbar">
          <div className="filter-tabs">
            <button className="filter-button active" type="button">
              全部
              <span>{skill.versions.length}</span>
            </button>
          </div>
          <div className="view-tools">
            <button className={clsx("icon-button", viewMode === "grid" && "active")} type="button" aria-label="卡片视图" onClick={() => setViewMode("grid")}>
              <Grid2X2 size={18} />
            </button>
            <button className={clsx("icon-button", viewMode === "list" && "active")} type="button" aria-label="列表视图" onClick={() => setViewMode("list")}>
              <List size={18} />
            </button>
          </div>
        </div>
        {viewMode === "grid" ? (
          <div className="version-grid">
            {skill.versions.map((version) => (
              <VersionCard
                key={version.id}
                version={version}
                currentVersionId={skill.skill.current_version_id}
                evalSetName={evalSetName}
                latestRun={latestRunForVersion(version, skill.latest_eval_runs)}
                active={selected?.id === version.id}
                onClick={() => onNavigate({ selectedVersionId: version.id })}
              />
            ))}
          </div>
        ) : (
          <div className="version-list-view">
            {skill.versions.map((version) => (
              <VersionListRow
                key={version.id}
                version={version}
                currentVersionId={skill.skill.current_version_id}
                evalSetName={evalSetName}
                latestRun={latestRunForVersion(version, skill.latest_eval_runs)}
                active={selected?.id === version.id}
                onClick={() => onNavigate({ selectedVersionId: version.id })}
              />
            ))}
          </div>
        )}
      </section>
      {uploadOpen ? (
        <aside className="version-upload-panel" aria-label="上传新版本">
          <div className="version-upload-head">
            <div>
              <h2>上传新版本</h2>
              <p>上传标准 Skill bundle 后会追加一个不可变 SkillVersion。</p>
            </div>
            <button className="icon-button" type="button" aria-label="关闭上传面板" onClick={onUploadClose}>
              <X size={18} />
            </button>
          </div>
          <VersionUploadForm
            skill={skill}
            actionsClassName="version-upload-actions"
            onCancel={onUploadClose}
            onUploaded={onUploaded}
          />
        </aside>
      ) : null}
      <aside className="version-detail-panel">
        {selected ? (
          <VersionInspector
            skill={skill}
            version={selected}
            evalSetName={evalSetName}
            latestRun={latestRunForVersion(selected, skill.latest_eval_runs)}
          />
        ) : (
          <div className="quiet-panel">还没有版本。</div>
        )}
      </aside>
    </div>
  );
}

function VersionCard({
  version,
  currentVersionId,
  evalSetName,
  latestRun,
  active,
  onClick,
}: {
  version: SkillVersion;
  currentVersionId: string | null;
  evalSetName: string;
  latestRun: EvalRunRecord | null;
  active: boolean;
  onClick: () => void;
}) {
  return (
    <button className={clsx("version-card", active && "active")} type="button" onClick={onClick}>
      <div className="version-card-head">
        <h3>{versionName(version)}</h3>
        {version.id === currentVersionId ? <CheckCircle2 size={23} /> : null}
      </div>
      <span className="version-pill">{version.id === currentVersionId ? "当前版本" : "历史版本"}</span>
      <div className="version-card-metrics">
        <span>
          <small>最新得分</small>
          <strong className={scoreKind(latestRun)}>{scoreLabel(latestRun)}</strong>
        </span>
        <span>
          <small>绑定测评集</small>
          <strong>{evalSetName}</strong>
        </span>
      </div>
      <p>{version.change_summary}</p>
    </button>
  );
}

function VersionListRow({
  version,
  currentVersionId,
  evalSetName,
  latestRun,
  active,
  onClick,
}: {
  version: SkillVersion;
  currentVersionId: string | null;
  evalSetName: string;
  latestRun: EvalRunRecord | null;
  active: boolean;
  onClick: () => void;
}) {
  return (
    <button className={clsx("version-list-row", active && "active")} type="button" onClick={onClick}>
      <strong>{versionName(version)}</strong>
      <span className="version-pill">{version.id === currentVersionId ? "当前" : "历史"}</span>
      <span className={scoreKind(latestRun)}>{scoreLabel(latestRun)}</span>
      <span>{evalSetName}</span>
      <small>{version.change_summary}</small>
    </button>
  );
}

function latestRunForVersion(version: SkillVersion, runs: EvalRunRecord[]): EvalRunRecord | null {
  return [...runs]
    .filter((run) => run.skill_version_id === version.id)
    .sort((left, right) => Date.parse(right.created_at ?? "") - Date.parse(left.created_at ?? ""))[0] ?? null;
}
