// apps/web/src/pages/VersionUploadForm.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import BundlePicker from "../components/BundlePicker.vue";
import { api, ApiError } from "../lib/api";
import { sourceFromFiles } from "../lib/bundle";
import type { SkillDetail } from "../types";

const props = withDefaults(defineProps<{ skill: SkillDetail; actionsClassName?: string }>(), { actionsClassName: "modal-actions" });
const emit = defineEmits<{ cancel: []; uploaded: [] }>();

const folderFiles = ref<File[]>([]);
const zipFile = ref<File | null>(null);
const displayName = ref("");
const busy = ref(false);
const error = ref<string | null>(null);
const canSubmit = computed(() => !busy.value && Boolean(zipFile.value || folderFiles.value.length));

async function submit(): Promise<void> {
  busy.value = true;
  error.value = null;
  try {
    const source = await sourceFromFiles(folderFiles.value, zipFile.value);
    await api.createSkillVersion({ skill_id: props.skill.skill.id, source, make_current: true, display_name: cleanName(displayName.value) });
    emit("uploaded");
  } catch (caught) {
    error.value = caught instanceof ApiError || caught instanceof Error ? caught.message : "上传失败。";
  } finally {
    busy.value = false;
  }
}

function cleanName(value: string): string | undefined {
  const clean = value.trim();
  return clean || undefined;
}
</script>

<template>
  <div class="form-stack">
    <div v-if="error" class="form-error">{{ error }}</div>
    <div class="hint-strip">将追加新的 SkillVersion，并设置为当前版本。</div>
    <label class="field-label">
      <span>版本名称</span>
      <input v-model="displayName" maxlength="80" :placeholder="`例如 ${skill.skill.slug} stable`" />
    </label>
    <BundlePicker
      @files="
        (nextFolderFiles, nextZipFile) => {
          folderFiles = nextFolderFiles;
          zipFile = nextZipFile;
        }
      "
    />
    <div :class="actionsClassName">
      <button class="secondary-button" type="button" @click="emit('cancel')">取消</button>
      <button class="primary-button" type="button" :disabled="!canSubmit" @click="submit">
        {{ busy ? "上传中..." : "确认上传" }}
      </button>
    </div>
  </div>
</template>

// apps/web-v4/src/pages/VersionUploadForm.tsx
import { useState } from "react";
import { BundlePicker } from "../components/BundlePicker";
import { api, ApiError } from "../lib/api";
import { sourceFromFiles } from "../lib/bundle";
import type { SkillDetail } from "../types";

type VersionUploadFormProps = {
  skill: SkillDetail;
  actionsClassName?: string;
  onCancel: () => void;
  onUploaded: () => Promise<void>;
};

export function VersionUploadForm({ skill, actionsClassName = "modal-actions", onCancel, onUploaded }: VersionUploadFormProps) {
  const [folderFiles, setFolderFiles] = useState<File[]>([]);
  const [zipFile, setZipFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const canSubmit = !busy && Boolean(zipFile || folderFiles.length);

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      const source = await sourceFromFiles(folderFiles, zipFile);
      await api.createSkillVersion({ skill_id: skill.skill.id, source, make_current: true });
      await onUploaded();
    } catch (caught) {
      setError(caught instanceof ApiError || caught instanceof Error ? caught.message : "上传失败。");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="form-stack">
      {error ? <div className="form-error">{error}</div> : null}
      <div className="hint-strip">将追加新的 SkillVersion，并设置为当前版本。</div>
      <BundlePicker
        onFiles={(nextFolderFiles, nextZipFile) => {
          setFolderFiles(nextFolderFiles);
          setZipFile(nextZipFile);
        }}
      />
      <div className={actionsClassName}>
        <button className="secondary-button" type="button" onClick={onCancel}>
          取消
        </button>
        <button className="primary-button" type="button" disabled={!canSubmit} onClick={submit}>
          {busy ? "上传中..." : "确认上传"}
        </button>
      </div>
    </div>
  );
}
