// apps/web/src/pages/EvaluatePage.tsx
import clsx from "clsx";
import { Info } from "lucide-react";
import { type CSSProperties, useCallback, useEffect, useMemo, useState } from "react";
import { EvaluationContextCard } from "../components/EvaluationContextCard";
import { EvaluationVersionSelectors } from "../components/EvaluationVersionSelectors";
import { ManualCase, ManualEvalActionBar, ManualProgressPanel } from "../components/ManualEvaluationPanels";
import { ManualVersionDetailPanel, type ManualVersionDetailFocus } from "../components/ManualVersionDetailPanel";
import { api, ApiError } from "../lib/api";
import { manualRecordHint, manualResultLabel, nextPendingCaseVersionId, summarizeManualEval, type ManualCaseResult } from "../lib/eval";
import type { RouteState } from "../lib/navigation";
import type { EvalSetDetail, SkillDetail, ToastState } from "../types";

type EvaluatePageProps = { skill: SkillDetail; onRefresh: () => Promise<void>; onNavigate: (next: Partial<RouteState>) => void; onToast: (toast: ToastState) => void };

export function EvaluatePage({ skill, onRefresh, onNavigate, onToast }: EvaluatePageProps) {
  const versions = skill.versions;
  const evalSet = skill.summary.primary_eval_set;
  const evalSetId = evalSet?.id ?? "";
  const defaultVersionId = skill.skill.current_version_id ?? versions[0]?.id ?? "";
  const [skillVersionId, setSkillVersionId] = useState(defaultVersionId);
  const [environmentTags, setEnvironmentTags] = useState<string[]>([]);
  const [detail, setDetail] = useState<EvalSetDetail | null>(null);
  const [results, setResults] = useState<Record<string, ManualCaseResult>>({});
  const [activeCaseId, setActiveCaseId] = useState<string | null>(null);
  const [versionDetailFocus, setVersionDetailFocus] = useState<ManualVersionDetailFocus | null>(null);
  const [busy, setBusy] = useState(false);
  const cases = useMemo(() => detail?.cases ?? [], [detail]);
  const summary = summarizeManualEval(cases.length, results);
  const active = cases.find((item) => item.case_version.id === activeCaseId) ?? cases[0] ?? null;
  const activePosition = active ? cases.findIndex((item) => item.case_version.id === active.case_version.id) + 1 : 0;
  const selectedVersion = versions.find((version) => version.id === skillVersionId);
  const activeResult = active ? results[active.case_version.id] : undefined;
  const activePassed = activeResult?.passed;
  const canRecord = !busy && Boolean(skillVersionId && evalSetId) && summary.pending === 0 && cases.length > 0;
  const canMoveNext = !busy && summary.pending > 0 && cases.length > 0;
  const progressStyle = { "--coverage": `${summary.coverage}%` } as CSSProperties;
  const recordHint = manualRecordHint(cases.length, summary.pending);

  useEffect(() => {
    if (!evalSetId) {
      setDetail(null);
      setActiveCaseId(null);
      setResults({});
      return;
    }
    let cancelled = false;
    api.getEvalSet(evalSetId).then((next) => {
      if (cancelled) return;
      setDetail(next);
      setActiveCaseId(next.cases[0]?.case_version.id ?? null);
      setResults({});
    }).catch((error) => onToast({ tone: "danger", message: errorMessage(error) }));
    return () => {
      cancelled = true;
    };
  }, [evalSetId, onToast]);

  const mark = useCallback((caseVersionId: string, passed: boolean) => {
    setResults((current) => ({
      ...current,
      [caseVersionId]: {
        actualOutput: current[caseVersionId]?.actualOutput ?? "",
        passed,
      },
    }));
  }, []);

  const updateActualOutput = useCallback((caseVersionId: string, actualOutput: string) => {
    setResults((current) => ({
      ...current,
      [caseVersionId]: {
        actualOutput,
        passed: current[caseVersionId]?.passed,
      },
    }));
  }, []);

  const goNext = useCallback(() => {
    const nextId = nextPendingCaseVersionId(cases, results, activeCaseId);
    if (nextId) setActiveCaseId(nextId);
  }, [activeCaseId, cases, results]);

  const copyText = useCallback(async (label: string, text?: string | null) => {
    const content = text ?? "";
    if (!content.trim()) return;
    try {
      await navigator.clipboard.writeText(content);
      onToast({ tone: "success", message: `${label} 已复制。` });
    } catch (caught) {
      onToast({ tone: "danger", message: errorMessage(caught) });
    }
  }, [onToast]);

  const recordRun = useCallback(async () => {
    if (!skillVersionId || !evalSetId || summary.pending > 0 || cases.length === 0) return;
    setBusy(true);
    try {
      const recorded = await api.recordEvalRun({
        skill_version_id: skillVersionId,
        eval_set_id: evalSetId,
        strategy: "manual_pass_fail",
        environment_tags: environmentTags,
        run_context: {},
        results: Object.fromEntries(
          Object.entries(results).map(([caseVersionId, result]) => [
            caseVersionId,
            { passed: result.passed === true, actual_output: result.actualOutput },
          ]),
        ),
      });
      onToast({ tone: "success", message: "测评结果已记录。" });
      await onRefresh();
      onNavigate({ tab: "history", selectedRunId: recorded.eval_run_id });
    } catch (caught) {
      onToast({ tone: "danger", message: errorMessage(caught) });
    } finally {
      setBusy(false);
    }
  }, [cases.length, environmentTags, evalSetId, onNavigate, onRefresh, onToast, results, skillVersionId, summary.pending]);

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (event.metaKey || event.ctrlKey || event.altKey || isTypingTarget(event.target)) return;
      const key = event.key.toLowerCase();
      if (/^[1-9]$/.test(key)) {
        const target = cases[Number(key) - 1];
        if (target) {
          event.preventDefault();
          setActiveCaseId(target.case_version.id);
        }
      }
      if (key === "p" && active) {
        event.preventDefault();
        mark(active.case_version.id, true);
      }
      if (key === "f" && active) {
        event.preventDefault();
        mark(active.case_version.id, false);
      }
      if (key === "n" && summary.pending > 0) {
        event.preventDefault();
        goNext();
      }
      if (key === "s" && canRecord) {
        event.preventDefault();
        void recordRun();
      }
    }

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [active, canRecord, cases, goNext, mark, recordRun, summary.pending]);

  return (
    <div className="evaluate-page">
      <section className="evaluation-selectors">
        <EvaluationVersionSelectors
          versions={versions}
          evalSet={evalSet}
          skillVersionId={skillVersionId}
          versionDetailFocus={versionDetailFocus}
          onSkillVersionChange={setSkillVersionId}
          onVersionDetailFocusChange={setVersionDetailFocus}
        />
        <EvaluationContextCard
          environmentTags={environmentTags}
          latestRuns={skill.latest_eval_runs}
          onEnvironmentTagsChange={setEnvironmentTags}
        />
        <div className="info-box">
          <Info size={18} />
          <div>
            <strong>在此页面执行人工测评</strong>
            <p>选择 SkillVersion，使用当前测评集逐条输入本次运行结果并记录环境上下文。</p>
          </div>
        </div>
        {versionDetailFocus ? (
            <ManualVersionDetailPanel
              focus={versionDetailFocus}
              skillVersion={selectedVersion}
              evalSet={evalSet}
              evalSetDetail={detail}
            onClose={() => setVersionDetailFocus(null)}
          />
        ) : null}
      </section>

      <ManualProgressPanel summary={summary} caseCount={cases.length} evalSetName={detail?.eval_set.name} progressStyle={progressStyle} />

      <div className="manual-eval-grid">
        <aside className="manual-case-list">
          <header className="manual-list-head">
            <div>
              <h2>Case 列表</h2>
              <p>{summary.pending} 个待评估</p>
            </div>
            <span>{cases.length}</span>
          </header>
          {cases.map((item, index) => {
            const result = results[item.case_version.id];
            const position = item.position + 1;
            const label = manualResultLabel(result?.passed);
            return (
              <button
                aria-current={active?.case_version.id === item.case_version.id ? "true" : undefined}
                aria-label={`${item.case.title}，#${position}，case v${item.case_version.version_number}，${label}`}
                className={clsx("manual-case-row", active?.case_version.id === item.case_version.id && "active")}
                type="button"
                key={item.case_version.id}
                onClick={() => setActiveCaseId(item.case_version.id)}
              >
                <span className={clsx("manual-status-dot", manualStatusClass(result?.passed))} aria-hidden="true" />
                <span className="manual-case-index">#{position}</span>
                <span className="manual-case-copy">
                  <strong>{item.case.title}</strong>
                  <small>
                    <span>case v{item.case_version.version_number}</span>
                    <span>{label}</span>
                  </small>
                </span>
                {index < 9 ? <kbd className="manual-shortcut-chip">{index + 1}</kbd> : null}
              </button>
            );
          })}
        </aside>
        <section className="manual-case-detail">
          {active ? (
            <ManualCase
              item={active}
              version={selectedVersion}
              result={activeResult}
              positionLabel={activePosition}
              onActualOutputChange={updateActualOutput}
              onCopy={copyText}
            />
          ) : (
            <div className="quiet-panel">没有可测评的 case。</div>
          )}
        </section>
      </div>

      <ManualEvalActionBar
        activePassed={activePassed}
        busy={busy}
        canMark={Boolean(active)}
        canMoveNext={canMoveNext}
        canRecord={canRecord}
        recordHint={recordHint}
        onPass={() => active && mark(active.case_version.id, true)}
        onFail={() => active && mark(active.case_version.id, false)}
        onNext={goNext}
        onRecord={recordRun}
      />
    </div>
  );
}

function isTypingTarget(target: EventTarget | null): boolean {
  if (!(target instanceof HTMLElement)) return false;
  return ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName) || target.isContentEditable;
}

function manualStatusClass(value?: boolean): string {
  if (value === true) return "passed";
  if (value === false) return "failed";
  return "pending";
}

function errorMessage(error: unknown): string {
  if (error instanceof ApiError || error instanceof Error) return error.message;
  return "操作失败。";
}

// apps/frontend/src/pages/EvaluatePage.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import DropdownSelect from "../components/DropdownSelect.vue";
import RunnerActionBar from "../features/evaluation/components/RunnerActionBar.vue";
import RunnerCaseDetail from "../features/evaluation/components/RunnerCaseDetail.vue";
import RunnerCaseQueue from "../features/evaluation/components/RunnerCaseQueue.vue";
import RunnerStatusBoard from "../features/evaluation/components/RunnerStatusBoard.vue";
import { useOpencodeEvaluation } from "../features/evaluation/composables/useOpencodeEvaluation";
import { api, ApiError } from "../lib/api";
import { runnerState } from "../features/evaluation/lib/evalRunner";
import { versionName } from "../lib/format";
import type { RouteState } from "../lib/navigation";
import type { EvalSetDetail, OpencodeModelSelection, OpencodeProviderCatalog, SkillDetail, ToastState } from "../types";

const props = defineProps<{ skill: SkillDetail; selectedEvalSetId: string | null }>();
const emit = defineEmits<{ refresh: []; navigate: [next: Partial<RouteState>]; toast: [toast: ToastState] }>();

const versions = computed(() => props.skill.versions);
const evalSets = computed(() => props.skill.eval_sets);
const fallbackEvalSetId = computed(() => props.skill.summary.primary_eval_set?.id ?? evalSets.value[0]?.id ?? "");
const evalSetId = computed(() => {
  const requested = props.selectedEvalSetId;
  return evalSets.value.some((item) => item.id === requested) ? requested ?? "" : fallbackEvalSetId.value;
});
const skillVersionId = ref(props.skill.skill.current_version_id ?? props.skill.versions[0]?.id ?? "");
const detail = ref<EvalSetDetail | null>(null);
const activeCaseId = ref<string | null>(null);
const modelCatalog = ref<OpencodeProviderCatalog | null>(null);
const modelError = ref("");
const modelLoading = ref(false);
const modelSelection = ref<OpencodeModelSelection | null>(null);
const cases = computed(() => detail.value?.cases ?? []);
const active = computed(() => cases.value.find((item) => item.case_version.id === activeCaseId.value) ?? null);
const selectedVersion = computed(() => versions.value.find((version) => version.id === skillVersionId.value));
const selectedVersionSummary = computed(() => cleanVersionSummary(selectedVersion.value?.change_summary));
const versionOptions = computed(() => versions.value.map((version) => ({ value: version.id, label: versionName(version) })));
const evalSetOptions = computed(() => evalSets.value.map((item) => ({ value: item.id, label: item.name, description: `${item.description || "暂无描述"} · ${item.id === fallbackEvalSetId.value ? "默认" : "自定义"}` })));
const evalSetLoaded = computed(() => Boolean(detail.value));
const canRunEvaluation = computed(() => Boolean(props.skill.capabilities?.permissions["eval.run"]));
const {
  board: opencodeBoard,
  busy,
  canRunFormalEvaluation,
  opencodeRunsByCase,
  pollIntervalSeconds,
  polling,
  runningCaseId,
  summary: opencodeSummary,
  actualOutputForCase,
  runAll,
  runCase,
  runFormalEvaluation,
  runForCase,
  retryFailed,
} = useOpencodeEvaluation({
  cases,
  skillVersionId,
  evalSetId,
  modelSelection,
  ready: evalSetLoaded,
  emitToast: (toast) => emit("toast", toast),
});
const activeRun = computed(() => (active.value ? runForCase(active.value.case_version.id) : null));
const activeRunState = computed(() => runnerState(activeRun.value));
const activeActualOutput = computed(() => actualOutputForCase(active.value?.case_version.id));

watch(evalSetId, async (id) => {
  if (!id) {
    detail.value = null;
    activeCaseId.value = null;
    return;
  }
  if (id !== props.selectedEvalSetId) emit("navigate", { selectedEvalSetId: id, selectedRunId: null });
  try {
    const next = await api.getEvalSet(id);
    detail.value = next;
    activeCaseId.value = null;
  } catch (caught) {
    emit("toast", { tone: "danger", message: errorMessage(caught) });
  }
}, { immediate: true });

watch(() => skillVersionId.value, () => {
  activeCaseId.value = null;
});

onMounted(() => window.addEventListener("keydown", onKeyDown));
onBeforeUnmount(() => {
  window.removeEventListener("keydown", onKeyDown);
});

async function loadOpencodeProviders(): Promise<void> {
  if (modelLoading.value) return;
  modelLoading.value = true;
  modelError.value = "";
  try {
    modelCatalog.value = await api.listOpencodeProviders();
  } catch (caught) {
    modelError.value = errorMessage(caught);
    modelCatalog.value = null;
  } finally {
    modelLoading.value = false;
  }
}

function selectOpencodeModel(selection: OpencodeModelSelection | null): void {
  modelSelection.value = selection;
}

async function copyText(label: string, text?: string | null): Promise<void> {
  const content = text ?? "";
  if (!content.trim()) return;
  try {
    await navigator.clipboard.writeText(content);
    emit("toast", { tone: "success", message: `${label} 已复制。` });
  } catch (caught) {
    emit("toast", { tone: "danger", message: errorMessage(caught) });
  }
}

async function runFormalOpencodeEvaluation(): Promise<void> {
  if (!canRunEvaluation.value) {
    emit("toast", { tone: "danger", message: "当前身份没有运行测评权限。" });
    return;
  }
  const evalRunId = await runFormalEvaluation();
  if (!evalRunId) return;
  emit("refresh");
  emit("navigate", { tab: "history", selectedEvalSetId: evalSetId.value, selectedRunId: evalRunId });
}

async function runActiveCase(): Promise<void> {
  if (!active.value) return;
  if (!canRunEvaluation.value) {
    emit("toast", { tone: "danger", message: "当前身份没有运行测评权限。" });
    return;
  }
  await runCase(active.value);
}

function onKeyDown(event: KeyboardEvent): void {
  if (event.metaKey || event.ctrlKey || event.altKey || isTypingTarget(event.target)) return;
  const key = event.key.toLowerCase();
  if (/^[1-9]$/.test(key)) {
    const target = cases.value[Number(key) - 1];
    if (target) {
      event.preventDefault();
      activeCaseId.value = target.case_version.id;
    }
  }
}

function isTypingTarget(target: EventTarget | null): boolean {
  if (!(target instanceof HTMLElement)) return false;
  return ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName) || target.isContentEditable;
}

function selectEvalSet(id: string): void {
  emit("navigate", { selectedEvalSetId: id, selectedRunId: null });
}

function errorMessage(caught: unknown): string {
  if (caught instanceof ApiError || caught instanceof Error) return caught.message;
  return "操作失败。";
}

function cleanVersionSummary(value?: string | null): string {
  const text = value?.trim() ?? "";
  if (!text || text.startsWith("Imported standard skill bundle with")) return "";
  return text;
}

</script>

<template>
  <div class="evaluate-page">
    <section class="evaluation-selectors">
      <div class="evaluation-selector-card">
        <label class="field-label">
          <span>Skill 版本</span>
          <DropdownSelect v-model="skillVersionId" :options="versionOptions" aria-label="选择 Skill 版本" />
        </label>
        <p v-if="selectedVersionSummary">{{ selectedVersionSummary }}</p>
      </div>
      <div class="evaluation-selector-card">
        <label class="field-label">
          <span>当前测评集</span>
          <DropdownSelect :model-value="evalSetId" :options="evalSetOptions" aria-label="选择测评集" @update:model-value="selectEvalSet" />
        </label>
      </div>
      <RunnerActionBar
        :busy="busy"
        :can-run-formal="canRunFormalEvaluation && canRunEvaluation"
        :case-count="cases.length"
        :disabled="!canRunEvaluation"
        :model-catalog="modelCatalog"
        :model-error="modelError"
        :model-loading="modelLoading"
        :model-selection="modelSelection"
        :poll-interval-seconds="pollIntervalSeconds"
        :summary="opencodeSummary"
        @refresh-models="loadOpencodeProviders"
        @retry-failed="retryFailed"
        @run-all="runAll"
        @run-formal="runFormalOpencodeEvaluation"
        @select-model="selectOpencodeModel"
      />
    </section>

    <section class="eval-progress-panel runner-progress-panel">
      <div class="progress-summary-card">
        <div class="progress-ring" :style="{ '--coverage': `${opencodeSummary.coverage}%` }">
          <span>{{ opencodeSummary.coverage }}%</span>
        </div>
        <div class="progress-copy">
          <span>进度</span>
          <h1>{{ opencodeSummary.confirmed }}/{{ cases.length }}</h1>
          <p>{{ opencodeSummary.pending }} 个测试例尚未完成，{{ opencodeSummary.failedRuns }} 个执行失败。</p>
        </div>
      </div>
      <div class="progress-metrics">
        <div class="progress-metric passed"><i /><strong>{{ opencodeSummary.passed }}</strong><small>通过</small></div>
        <div class="progress-metric failed"><i /><strong>{{ opencodeSummary.failed }}</strong><small>不通过</small></div>
        <div class="progress-metric pending"><i /><strong>{{ opencodeSummary.pending }}</strong><small>待评估</small></div>
      </div>
      <RunnerStatusBoard :items="opencodeBoard" />
    </section>

    <div class="evaluation-runner-grid">
      <RunnerCaseQueue
        :active-case-id="active?.case_version.id ?? null"
        :cases="cases"
        :pending="opencodeSummary.pending"
        :runs-by-case="opencodeRunsByCase"
        @select="activeCaseId = $event"
      />
      <RunnerCaseDetail
        :active="active"
        :actual-output="activeActualOutput"
        :poll-interval-seconds="pollIntervalSeconds"
        :polling="polling"
        :run="activeRun"
        :running-case-id="runningCaseId"
        :state="activeRunState"
        @copy="copyText"
        @run="runActiveCase"
      />
      <p v-if="!canRunEvaluation" class="field-help permission-hint">当前身份没有运行测评权限，需要 evaluator、maintainer、owner 或 admin 角色。</p>
    </div>
  </div>
</template>
