// apps/web-v4/src/pages/NewSkillModal.tsx
import { useState } from "react";
import { BundlePicker } from "../components/BundlePicker";
import { Modal } from "../components/Modal";
import { api, ApiError } from "../lib/api";
import { sourceFromFiles } from "../lib/bundle";

type NewSkillModalProps = {
  actor: string;
  onClose: () => void;
  onCreated: (skillId: string) => Promise<void>;
};

export function NewSkillModal({ actor, onClose, onCreated }: NewSkillModalProps) {
  const [folderFiles, setFolderFiles] = useState<File[]>([]);
  const [zipFile, setZipFile] = useState<File | null>(null);
  const [displayName, setDisplayName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      const source = await sourceFromFiles(folderFiles, zipFile);
      const created = await api.importSkill({ owner_ref: actor, source, display_name: cleanName(displayName) });
      await onCreated(created.skill_id);
    } catch (caught) {
      setError(caught instanceof ApiError || caught instanceof Error ? caught.message : "创建失败。");
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal title="新建 Skill" description="上传标准 Skill bundle，名称和说明会从 SKILL.md frontmatter 读取。" onClose={onClose}>
      <div className="form-stack">
        {error ? <div className="form-error">{error}</div> : null}
        <label className="field-label">
          <span>初始版本名称</span>
          <input value={displayName} maxLength={80} placeholder="例如 first usable build" onChange={(event) => setDisplayName(event.target.value)} />
        </label>
        <BundlePicker
          onFiles={(nextFolderFiles, nextZipFile) => {
            setFolderFiles(nextFolderFiles);
            setZipFile(nextZipFile);
          }}
        />
        <div className="modal-actions">
          <button className="secondary-button" type="button" onClick={onClose}>
            取消
          </button>
          <button className="primary-button" type="button" disabled={busy || (!zipFile && folderFiles.length === 0)} onClick={submit}>
            {busy ? "创建中..." : "创建 Skill"}
          </button>
        </div>
      </div>
    </Modal>
  );
}

function cleanName(value: string): string | undefined {
  const clean = value.trim();
  return clean || undefined;
}

// apps/web/src/pages/NewSkillModal.vue
<script setup lang="ts">
import { ref } from "vue";
import BundlePicker from "../components/BundlePicker.vue";
import Modal from "../components/Modal.vue";
import { api, ApiError } from "../lib/api";
import { sourceFromFiles } from "../lib/bundle";

const props = defineProps<{ actor: string }>();
const emit = defineEmits<{ close: []; created: [skillId: string] }>();

const folderFiles = ref<File[]>([]);
const zipFile = ref<File | null>(null);
const displayName = ref("");
const busy = ref(false);
const error = ref<string | null>(null);

async function submit(): Promise<void> {
  busy.value = true;
  error.value = null;
  try {
    const source = await sourceFromFiles(folderFiles.value, zipFile.value);
    const created = await api.importSkill({ owner_ref: props.actor, source, display_name: cleanName(displayName.value) });
    emit("created", created.skill_id);
  } catch (caught) {
    error.value = caught instanceof ApiError || caught instanceof Error ? caught.message : "创建失败。";
  } finally {
    busy.value = false;
  }
}

function cleanName(value: string): string | undefined {
  const clean = value.trim();
  return clean || undefined;
}
</script>

<template>
  <Modal title="新建 Skill" description="上传标准 Skill bundle，名称和说明会从 SKILL.md frontmatter 读取。" @close="emit('close')">
    <div class="form-stack">
      <div v-if="error" class="form-error">{{ error }}</div>
      <label class="field-label">
        <span>初始版本名称</span>
        <input v-model="displayName" maxlength="80" placeholder="例如 first usable build" />
      </label>
      <BundlePicker
        @files="
          (nextFolderFiles, nextZipFile) => {
            folderFiles = nextFolderFiles;
            zipFile = nextZipFile;
          }
        "
      />
      <div class="modal-actions">
        <button class="secondary-button" type="button" @click="emit('close')">取消</button>
        <button class="primary-button" type="button" :disabled="busy || (!zipFile && folderFiles.length === 0)" @click="submit">
          {{ busy ? "创建中..." : "创建 Skill" }}
        </button>
      </div>
    </div>
  </Modal>
</template>
