// apps/frontend/src/pages/SkillEditForm.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import BundleEditor from "../components/BundleEditor.vue";
import VersionSelector from "../components/VersionSelector.vue";
import { api, ApiError } from "../lib/api";
import { nextPatchVersion, validSemver } from "../lib/semver";
import type { BundleFile, BundleSource, SkillDetail, SkillVersion } from "../types";

const ENTRY_PATH = "SKILL.md";

const props = withDefaults(defineProps<{ skill: SkillDetail; version: SkillVersion; actionsClassName?: string }>(), { actionsClassName: "modal-actions" });
const emit = defineEmits<{ cancel: []; saved: [] }>();

const files = computed(() => props.version.bundle_files ?? []);
const entryFile = computed(() => files.value.find((file) => file.path === ENTRY_PATH) ?? null);
const drafts = ref(textDrafts(files.value));
const version = ref(nextPatchVersion(props.skill.versions));
const displayName = ref("");
const changeSummary = ref(`基于 ${versionLabel(props.version)} 编辑 Skill 内容。`);
const busy = ref(false);
const error = ref<string | null>(null);
const missingBinaryContent = computed(() => files.value.some((file) => file.binary && !file.content_base64));
const canSubmit = computed(
  () =>
    !busy.value &&
    files.value.length > 0 &&
    validSemver(version.value) &&
    Boolean(entryFile.value && !entryFile.value.binary && drafts.value[ENTRY_PATH]?.trim() && changeSummary.value.trim() && !missingBinaryContent.value),
);

async function submit(): Promise<void> {
  busy.value = true;
  error.value = null;
  try {
    await api.createSkillVersion({
      skill_id: props.skill.skill.id,
      source: sourceFromBundle(files.value, drafts.value, props.skill.skill.slug),
      make_current: true,
      version: version.value.trim(),
      display_name: cleanOptional(displayName.value),
      change_summary: changeSummary.value.trim(),
    });
    emit("saved");
  } catch (caught) {
    error.value = caught instanceof ApiError || caught instanceof Error ? caught.message : "保存失败。";
  } finally {
    busy.value = false;
  }
}

function sourceFromBundle(bundleFiles: BundleFile[], values: Record<string, string>, slug: string): BundleSource {
  return {
    kind: "files",
    name: slug,
    files: bundleFiles.map((file) => filePayload(file, values)),
  };
}

function filePayload(file: BundleFile, values: Record<string, string>): { path: string; content_text?: string; content_base64?: string } {
  if (!file.binary) return { path: file.path, content_text: values[file.path] ?? file.content_text ?? "" };
  if (file.content_base64) return { path: file.path, content_base64: file.content_base64 };
  throw new Error(`当前 bundle 的二进制文件 ${file.path} 缺少内容，无法从页面编辑保存。`);
}

function textDrafts(bundleFiles: BundleFile[]): Record<string, string> {
  return Object.fromEntries(bundleFiles.filter((file) => !file.binary).map((file) => [file.path, file.content_text ?? ""]));
}

function cleanOptional(value: string): string | undefined {
  const clean = value.trim();
  return clean || undefined;
}

function versionLabel(version: SkillVersion): string {
  return version.display_name?.trim() || version.version || `v${version.version_number}`;
}
</script>

<template>
  <div class="form-stack skill-edit-form">
    <div v-if="error" class="form-error">{{ error }}</div>
    <div class="hint-strip">保存后会追加新的 Skill 版本，并设置为当前版本。</div>
    <div v-if="!entryFile" class="form-error">当前 bundle 找不到根目录 SKILL.md，无法使用页面编辑。</div>
    <div v-if="entryFile?.binary" class="form-error">SKILL.md 不是可编辑文本文件。</div>
    <div v-if="missingBinaryContent" class="form-error">当前 bundle 有缺少内容的二进制文件，无法从页面编辑保存。</div>
    <VersionSelector v-model="version" :versions="skill.versions" />
    <label class="field-label">
      <span>版本名称</span>
      <input v-model="displayName" maxlength="80" :placeholder="`例如 ${skill.skill.slug} edited`" />
    </label>
    <label class="field-label">
      <span>版本说明</span>
      <input v-model="changeSummary" maxlength="500" />
    </label>
    <BundleEditor
      :files="files"
      :drafts="drafts"
      :root-label="skill.skill.slug"
      @draft-change="
        (path, content) => {
          drafts = { ...drafts, [path]: content };
        }
      "
    />
    <div :class="actionsClassName">
      <button class="secondary-button" type="button" @click="emit('cancel')">取消</button>
      <button class="primary-button" type="button" :disabled="!canSubmit" @click="submit">
        {{ busy ? "保存中..." : "保存为新版本" }}
      </button>
    </div>
  </div>
</template>

// apps/web/src/pages/SkillEditForm.tsx
import { useState } from "react";
import { BundleEditor } from "../components/BundleEditor";
import { api, ApiError } from "../lib/api";
import type { BundleFile, BundleSource, SkillDetail, SkillVersion } from "../types";

type SkillEditFormProps = {
  skill: SkillDetail;
  version: SkillVersion;
  actionsClassName?: string;
  onCancel: () => void;
  onSaved: () => Promise<void>;
};

const ENTRY_PATH = "SKILL.md";

export function SkillEditForm({ skill, version, actionsClassName = "modal-actions", onCancel, onSaved }: SkillEditFormProps) {
  const files = version.bundle_files ?? [];
  const entryFile = version.bundle_files?.find((file) => file.path === ENTRY_PATH) ?? null;
  const [drafts, setDrafts] = useState(() => textDrafts(files));
  const [displayName, setDisplayName] = useState("");
  const [changeSummary, setChangeSummary] = useState(`基于 ${versionLabel(version)} 编辑 Skill 内容。`);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const missingBinaryContent = files.some((file) => file.binary && !file.content_base64);
  const canSubmit = !busy && files.length > 0 && Boolean(entryFile && !entryFile.binary && drafts[ENTRY_PATH]?.trim() && changeSummary.trim() && !missingBinaryContent);

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      await api.createSkillVersion({
        skill_id: skill.skill.id,
        source: sourceFromBundle(files, drafts, skill.skill.slug),
        make_current: true,
        display_name: cleanOptional(displayName),
        change_summary: changeSummary.trim(),
      });
      await onSaved();
    } catch (caught) {
      setError(caught instanceof ApiError || caught instanceof Error ? caught.message : "保存失败。");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="form-stack skill-edit-form">
      {error ? <div className="form-error">{error}</div> : null}
      <div className="hint-strip">保存后会追加新的 SkillVersion，并设置为当前版本。</div>
      {!entryFile ? <div className="form-error">当前 bundle 找不到根目录 SKILL.md，无法使用页面编辑。</div> : null}
      {entryFile?.binary ? <div className="form-error">SKILL.md 不是可编辑文本文件。</div> : null}
      {missingBinaryContent ? <div className="form-error">当前 bundle 有缺少内容的二进制文件，无法从页面编辑保存。</div> : null}
      <label className="field-label">
        <span>版本名称</span>
        <input value={displayName} maxLength={80} placeholder={`例如 ${skill.skill.slug} edited`} onChange={(event) => setDisplayName(event.target.value)} />
      </label>
      <label className="field-label">
        <span>版本说明</span>
        <input value={changeSummary} maxLength={500} onChange={(event) => setChangeSummary(event.target.value)} />
      </label>
      <BundleEditor files={files} drafts={drafts} rootLabel={skill.skill.slug} onDraftChange={(path, content) => setDrafts((current) => ({ ...current, [path]: content }))} />
      <div className={actionsClassName}>
        <button className="secondary-button" type="button" onClick={onCancel}>
          取消
        </button>
        <button className="primary-button" type="button" disabled={!canSubmit} onClick={submit}>
          {busy ? "保存中..." : "保存为新版本"}
        </button>
      </div>
    </div>
  );
}

function sourceFromBundle(files: BundleFile[], drafts: Record<string, string>, slug: string): BundleSource {
  return {
    kind: "files",
    name: slug,
    files: files.map((file) => filePayload(file, drafts)),
  };
}

function filePayload(file: BundleFile, drafts: Record<string, string>): { path: string; content_text?: string; content_base64?: string } {
  if (!file.binary) return { path: file.path, content_text: drafts[file.path] ?? file.content_text ?? "" };
  if (file.content_base64) return { path: file.path, content_base64: file.content_base64 };
  throw new Error(`当前 bundle 的二进制文件 ${file.path} 缺少内容，无法从页面编辑保存。`);
}

function textDrafts(files: BundleFile[]): Record<string, string> {
  return Object.fromEntries(files.filter((file) => !file.binary).map((file) => [file.path, file.content_text ?? ""]));
}

function cleanOptional(value: string): string | undefined {
  const clean = value.trim();
  return clean || undefined;
}

function versionLabel(version: SkillVersion): string {
  return version.display_name?.trim() || `v${version.version_number}`;
}
